### ISSUE TITLE
java.lang.IllegalStateException: ViewModel is not ready. Are you calling this method before Activity/Fragment onCreate?

### ISSUE THREAD

**Issue by arunkrishna2992** [inloop/AndroidViewModel#39]
I have a Fragment and a Viewpager (FragmentStatePagerAdapter) inside that. I'm trying to access the ViewModel of one of the child fragments (in Viewpager)  from parent fragment. Its working fine but when orientation changes it crashes with "java.lang.IllegalStateException: ViewModel is not ready"
Why is this happening?

**Comment by DanielNovak** [comment]
@arunkrishna2992 can you please provide sample code? Or at least stacktrace from the crash?
Also we recommend to use [ViewModelStatePagerAdapter ](https://github.com/inloop/AndroidViewModel/blob/master/library/src/main/java/eu/inloop/viewmodel/support/ViewModelStatePagerAdapter.java) instead of the regular FragmentStatePagerAdapter to prevent leaks.

**Comment by arunkrishna2992** [comment]
Ok i'm now using ViewModelStatePagerAdapter. 
Please see the stacktrace

03-19 12:08:29.543 24902-24902/com.xxx.xxx.xx.xx.for.xx.xxx.debug.qa E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                            Process: com.xxx.xxx.xx.xx.for.xx.xxx..debug.qa, PID: 24902
                                                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx.xx.xx.for.xx.xxx..debug.qa/com.cxxx.xxx.xx.xx.for.xx.xxx..ChatActivity}: java.lang.IllegalStateException: ViewModel is not ready. Are you calling this method before Activity/Fragment onCreate?
                                                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                                                at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
                                                                                                                at android.app.ActivityThread.-wrap15(ActivityThread.java)
                                                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
                                                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                                             Caused by: java.lang.IllegalStateException: ViewModel is not ready. Are you calling this method before Activity/Fragment onCreate?
                                                                                                                at eu.inloop.viewmodel.ViewModelHelper.getViewModel(ViewModelHelper.java:230)
                                                                                                                at eu.inloop.viewmodel.base.ViewModelBaseFragment.getViewModel(ViewModelBaseFragment.java:81)
                                                                                                                at com.xxx.xxx.xx.ui.fragments.ChatFileListingFragmnet.filterFiles(ChatFileListingFragmnet.java:450)
                                                                                                                at com.xxx.xxx.xx.ui.fragments.ChatFilesAndVaultsFragment.filterEkamChatFiles(ChatFilesAndVaultsFragment.java:231)
                                                                                                                at com.xxx.xxx.xx.viewmodel.ChatFilesAndVaultsViewModel.search(ChatFilesAndVaultsViewModel.java:52)
                                                                                                                at com.xxx.xxx.xx.ui.fragments.ChatFilesAndVaultsFragment$2.onQueryTextChange(ChatFilesAndVaultsFragment.java:173)
                                                                                                                at android.support.v7.widget.SearchView.onTextChanged(SearchView.java:1180)
                                                                                                                at android.support.v7.widget.SearchView$10.onTextChanged(SearchView.java:1714)
                                                                                                                at android.widget.TextView.sendOnTextChanged(TextView.java:7988)
                                                                                                                at android.widget.TextView.setText(TextView.java:4350)
                                                                                                                at android.widget.TextView.setText(TextView.java:4204)
                                                                                                                at android.widget.EditText.setText(EditText.java:84)
                                                                                                                at android.widget.TextView.setText(TextView.java:4179)
                                                                                                                at android.widget.TextView.onRestoreInstanceState(TextView.java:4072)
                                                                                                                at android.view.View.dispatchRestoreInstanceState(View.java:14752)
                                                                                                                at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                                                                                at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                                                                                at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                                                                                at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                                                                                at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                                                                                at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                                                                                at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                                                                                at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                                                                                at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                                                                                at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
                                                                                                                at android.view.View.restoreHierarchyState(View.java:14730)
                                                                                                                at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2035)
                                                                                                                at android.app.Activity.onRestoreInstanceState(Activity.java:1008)
                                                                                                                at android.app.Activity.performRestoreInstanceState(Activity.java:963)
                                                                                                                at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1163)
                                                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2389)
                                                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                                                at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077) 
                                                                                                                at android.app.ActivityThread.-wrap15(ActivityThread.java) 
                                                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350) 
                                                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 


The method is getting called after calling setModelView()
